apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: kafka-consumer-springboot-cm
data:
  application.yml: |-
    kafka.topic.name: personne-topic
    server.port: 8080
    spring.kafka.bootstrap-servers: kafka-kafka-bootstrap:9092
    spring.kafka.properties.sasl.mechanism: SCRAM-SHA-512 
    spring.kafka.properties.security.protocol: SASL_SSL
    spring.kafka.properties.ssl.truststore.location: /truststore/ca.p12
    
    #spring.kafka.properties.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="@@username@@" password="@@password@@";
    #spring.kafka.properties.ssl.truststore.password: @@JKS_PASSWORD@@

    spring.datasource.url: jdbc:mysql://mysql:3306/cdc
    kafka.consumer.group-id: consumers-personne