apiVersion: v1
data:
  application.properties: |
    kafka.topic.name=livre-topic
    kafka.bootstrap.servers=kafka-kafka-bootstrap:9092
    mp.messaging.incoming.livres.bootstrap.servers=kafka-kafka-bootstrap:9092

    quarkus.config.locations=file:/database-param-quarkus/application-secret.properties
    quarkus.datasource.jdbc.url=jdbc:mysql://mysql:3306/cdc

    
kind: ConfigMap
metadata:
  name: kafka-consumer-quarkus-cm


 