apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: kafka-consumer-quarkus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-consumer-quarkus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-consumer-quarkus
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - env:
        - name: truststorepassword
          valueFrom:
            secretKeyRef:
              key: ca.password
              name: kafka-cluster-ca-cert
        envFrom:
        - secretRef:
            name: kafka-consumer-quarkus-user
        image: quay.io/olivierits4u/kafka-consumer-quarkus:1.0.0
        imagePullPolicy: Always

        name: kafka-consumer-quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /truststore
          name: truststore-volume
        - mountPath: /home/jboss/config
          name: kafka-consumer-quarkus-cm
          readOnly: true
        - name: database-param-quarkus
          mountPath: /database-param-quarkus

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: database-param-quarkus
        secret:
          secretName: database-param-quarkus
      - name: truststore-volume
        secret:
          optional: false
          secretName: kafka-cluster-ca-cert
      - configMap:
          name: kafka-consumer-quarkus-cm
        name: kafka-consumer-quarkus-cm
