apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    template:
      pod:
        affinity:
#          nodeAffinity:
#            preferredDuringSchedulingIgnoredDuringExecution:
#              - weight: 1
#                preference: 
#                  matchExpressions:
#                  - key: topology.kubernetes.io/zone
#                    operator: In
#                    values:
#                    - dc1
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - kafka
              topologyKey: kubernetes.io/hostname
    version: 3.6.0
    replicas: 3
    listeners:
      - name: full
        port: 9092
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: lm
        port: 9093
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
    authorization: 
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: true
      log.message.format.version: "3.6"
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
  zookeeper:
    template:
      pod:
        affinity:
#          nodeAffinity:
#            preferredDuringSchedulingIgnoredDuringExecution:
#              - weight: 1
#                preference: 
#                  matchExpressions:
#                  - key: topology.kubernetes.io/zone
#                    operator: In
#                    values:
#                    - dc2
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - zookeeper
              topologyKey: kubernetes.io/hostname
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true   
  entityOperator:
    topicOperator: {}
    userOperator: {}
 


