apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-producer-springboot
  name: kafka-producer-springboot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-producer-springboot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-producer-springboot
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: quay.io/olivierits4u/kafka-producer-springboot:1.0.0
        imagePullPolicy: Always
        name: kafka-producer-springboot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: JDK_JAVA_OPTIONS
          value: "-Dspring.config.additional-location=file:/config/application.yml"
       
        - name: TZ
          value: "Europe/Luxembourg"
        - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafka-producer-springboot-user
              key: sasl.jaas.config
        - name: SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-cluster-ca-cert
              key: ca.password
        volumeMounts:
        - name: kafka-producer-springboot-cm
          mountPath: /config
        - name: kafka-producer-springboot-truststore
          mountPath: /truststore
       
      volumes:
        - name: kafka-producer-springboot-cm
          configMap:
            name: kafka-producer-springboot-cm
        - name: kafka-producer-springboot-truststore
          secret:
            secretName: kafka-cluster-ca-cert
       
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
