apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-consumer-springboot-user
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: personne-topic
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: consumers-personne
        operations:
          - Describe
          - Read
     