apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-ui-user
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All  
      - resource:
          type: cluster
          name: '*'
          patternType: literal
        operation: All  
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: All  
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operation: All 
